version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    parallelism: 1
    working_directory: ~/huynhhau/findmykids-web 
    steps:
      - checkout
      - attach_workspace:
          at: ~/huynhhau/findmykids-web
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: dist

  deploy:
    docker:
      - image: circleci/golang:1.9.6
    parallelism: 1
    working_directory: ~/huynhhau/findmykids-web
    steps:
      - checkout
      - attach_workspace:
          at: ~/huynhhau/findmykids-web
      - restore_cache:
          key: v1-pkg-cache
      - run: go get -v github.com/huynhhau/findmykids-web
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg
      - run:
          name: Deploy to S3
          command: |
            s3deploy -source=dist/ -region=us-west-2 -bucket=findmykids

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master